---
- name: Update and upgrade apt packages
  become: true
  apt:
      upgrade: yes
      update_cache: yes

- name: Docker Installation - adding docker repository
  shell: |   
    sudo apt-get update
    sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo apt-key fingerprint 0EBFCD88
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Docker Installation - repository installation
  shell: |
    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io
    sudo chmod 777 /var/run/docker.sock
    sudo apt install -y gnupg2 pass
    sudo groupadd docker
    sudo usermod -aG docker jenkins
    sudo chmod 777 /var/run/docker.sock