apiVersion: v1
kind: Service
metadata:
  name: pollerinternal
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
  selector:
    {{- include "poller.selectorLabels" . | nindent 4 }}