---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secret.dockercred.name }}-{{ .Release.Name }}
    namespace: {{ .Values.namespace.name }}
    labels:
     {{- include "poller.labels" . | nindent 5 }}
data:
    .dockerconfigjson: {{ .Values.secret.dockercred.dockerconfigjson }}
type: {{ .Values.secret.dockercred.type }}