apiVersion: v1
kind: Service
metadata:
  name: notifierinternal
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  ports:
    - port: 9094  
      targetPort: 9094
  selector:
    {{- include "notifier.selectorLabels" . | nindent 4 }}