apiVersion: v1
kind: Service
metadata:
  name: backendinternal
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}