- hosts: localhost
  gather_facts: false
  user: root
  roles:
    - {role: 'setup__cluster', tags: 'create'}
    - {role: 'metrics-server', tags: 'metrics'}
    - {role: 'cluster-autoscaler', tags: 'autoscaler'}