---
# Creating RDS Instances
- name: Create rds instance
  rds:
    command:  create
    backup_retention: 0
    instance_name:  "{{ rds_instance_name }}"
    instance_type: db.t2.micro
    db_engine: MySQL
    db_name: "{{ rds_dbname }}"
    size: 20
    multi_zone: no
    region: "{{ region }}"
    publicly_accessible: false
    subnet: "{{ rds_subnet_group.subnet_group.name }}"
    vpc_security_groups: "{{ db_security_group.group_id }}"
    username: "{{ rds_username }}"
    password: "{{ rds_password }}"
    tags:
      Application: backendDB
    wait: yes
  register: rdskubernetes

...